# Generated by Django 5.2 on 2026-04-07 14:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('titulo_original', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(help_text='Ex: Drama, Sci-Fi', max_length=255)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('diretor', models.CharField(blank=True, max_length=255, null=True)),
                ('ano_lancamento', models.IntegerField(blank=True, null=True)),
                ('duracao_minutos', models.IntegerField(default=0)),
                ('metadados', models.JSONField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='filmes/posters')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='Filme_assistido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_finalizacao', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_que_assistiram', to='app_Goodfilms.filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_assistidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Filme_assistidos',
            },
        ),
        migrations.CreateModel(
            name='Filme_visualizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='app_Goodfilms.filme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmes_vistos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Filme_visualizacao',
            },
        ),
        migrations.CreateModel(
            name='Filme_avaliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app_Goodfilms.filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Filme_avaliacao',
                'unique_together': {('user', 'filme')},
            },
        ),
        migrations.CreateModel(
            name='Filme_favoritos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='app_Goodfilms.filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Filme_favoritos',
                'unique_together': {('user', 'filme')},
            },
        ),
    ]
