# Generated by Django 5.2 on 2026-04-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Goodfilms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
