# Generated by Django 5.2 on 2026-04-28 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Goodfilms', '0002_remove_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(choices=[('Livre', 'Livre'), ('10 anos', '10 anos'), ('12 anos', '12 anos'), ('14 anos', '14 anos'), ('16 anos', '16 anos'), ('18 anos', '18 anos')], default='Livre', max_length=20),
        ),
        migrations.AlterField(
            model_name='filme',
            name='duracao_minutos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
